flask_app/APP/models/__init__.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/15  20:55
# @AUTHOR   : LXH
# @FILE     : __init__.py.py

flask_app/APP/__init__.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/15  19:47
# @AUTHOR   : LXH
# @FILE     : __init__.py.py # 创建app方法

from flask import Flask
from .config import config  # 导入文件，不是导入类
# from APP.config import Config # 存放有 密钥，不需要单独使用，选择环境时候就会携带
from .extensions import config_extensions # 第三方插件方法
from .views import config_blueprint # 蓝本


def create_app(config_name):
    # 实例化一个app对象
    app = Flask(__name__)

    app.config.from_object(config.get(config_name)) # 传入名字，选择环境与通用配置

    config.get(config_name).int_app(app) # 静态方法的安装,加载额外配置

    config_extensions(app) # 加载扩展

    config_blueprint(app) # 激活蓝本

    # 返回加载好的app对象
    return app

flask_app/APP/form/__init__.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/16  10:57
# @AUTHOR   : LXH
# @FILE     : __init__.py.py

# 初始化表格
from .f_wtf_ import NameForm

flask_app/APP/views/__init__.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/15  20:54
# @AUTHOR   : LXH
# @FILE     : __init__.py.py # 创建各种蓝本的地方

# 导入蓝本
from .user_ import user
from .moment_time import moment
from .log_original_form import o_form
from .f_wtf import f_wft


# 装蓝本的元组
BASE_BLUEPRINT = (
    (user,'/user'),
    (moment,'/moment'),
    (o_form,'/o_form'),
    (f_wft,'/f_wtf'),

)

# 循环便利存放蓝本的元组
def config_blueprint(app):
    for blueprint_name,url_prefix in BASE_BLUEPRINT:
        app.register_blueprint(blueprint=blueprint_name, url_prefix=url_prefix)
    pass

flask_app/APP/views/choose_test.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/16  23:53
# @AUTHOR   : LXH
# @FILE     : choose_test.py # 测试一些东西

# from APP.config import Config
#
# print(Config.SECRET_KEY)

flask_app/APP/views/f_wtf.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/16  23:14
# @AUTHOR   : LXH
# @FILE     : f_wtf.py # flask-wtf
from flask import Blueprint, render_template

# 导入表基类
from APP.form.f_wtf_ import NameForm

f_wft = Blueprint('f_wtf',__name__)


@f_wft.route('/wtf/', methods = ['POST','GET'])
def wtf():
    # 创建表单对象
    form = NameForm()
    # 渲染时候分配到模板文件
    return render_template('f_wtf.html', form=form)

flask_app/APP/views/log_original_form.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/16  20:41
# @AUTHOR   : LXH
# @FILE     : log_original_form.py # 原生表单
from flask import Blueprint, render_template, request
# from __future__ import print_function # 这是使用python新功能的包

o_form = Blueprint('o_form', __name__)


# @o_form.route('/form/<username>/', methods=['POST', 'GET'])
# def form(username):
#     if request.method == 'POST':
#         pass
#     return render_template('original_form.html', username=username)

@o_form.route('/form/',methods=['POST', 'GET'])
def form():
    username = 'god'
    if request.method == 'POST':
        username = request.form['username']
        return render_template('original_form.html',username = username)

    return render_template('original_form.html',username = username)

flask_app/APP/views/moment_time.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/16  11:43
# @AUTHOR   : LXH
# @FILE     : moment_time.py

from flask import Blueprint, render_template
from datetime import datetime, timedelta

moment = Blueprint('moment',__name__)


# 测试时间模块
@moment.route('/timies/')
def timeies():
    current_time = datetime.utcnow() # utc世界标准时间
    return render_template('moment.html',current_time=current_time)

@moment.route('/bootstrap_time/')
def bootstrap_time():
    # -3600 向前推迟一个小时（过去）
    # 3600 向后推一个小时（未来）
    current_time = datetime.utcnow() + timedelta(seconds=-3600)
    return render_template('bootstrap.html', current_time=current_time)

flask_app/APP/views/user_.py
# -*- coding:utf-8 -*-
# @TIME     : 2018/10/15  23:04
# @AUTHOR   : LXH
# @FILE     : user_.py

from flask import Blueprint


user = Blueprint('user',__name__)

@user.route('/hello_flask/')
def hello_flask():
    return 'hello flask'

flask_app/APP/templates/bace.html
{% extends 'bootstrap/base.html' %}

flask_app/APP/templates/bootstrap.html
{% extends 'bace.html' %}
{#{% extends 'bootstrap/base.html' %}#}

{% block content %}
    <div align='center'>
        时间日期：{{ moment(current_time).format('LLL') }}
        <hr>
        私人定制：{{ moment(current_time).format('YYYY-MM-DD') }}
        <hr>
        发表时间：{{ moment(current_time).fromNow() }}
        <hr>
    </div>

{% endblock %}



{# 导入js #}
{% block scripts %}
    {{ super() }}
{#    改写成中文,默认为英文 #}
    {{ moment.include_moment()}}
    {{ moment.locale('zh-CN') }}
{% endblock %}

flask_app/APP/templates/f_wtf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#    原生表单渲染#}
{#    判断是否有错误#}
{% if form.errors %}
    {#        可以存放多个错误信息，所以它是个列表，用索引取值#}
    {{ form.errors[0] }}
{% endif %}
<form action="{{ url_for('f_wtf.wtf') }}" method="post">
    {#        {{ form.hidden_tag }} 里面存放的是csrf_token，可以使用，跨站请求伪造，用来防止伪造的#}
    {{ form.csrf_token }} {# 这个也就是单独从hidden_tag拿出来的,hidden_tag 是可以隐藏的，这里使用这个来了解里面的加密#}
    {{ form.name.label() }}{{ form.name(id='xx', class='yyy') }}
    <hr>
    {{ form.submit() }}
</form>
</body>
</html>

flask_app/APP/templates/moment.html
{% extends 'bace.html' %}
{#{% extends 'bootstrap/base.html' %}#}

{% block content %}
    <div align='center'>
        时间日期：{{ moment(current_time).format('LLL') }}
        <hr>
        私人定制：{{ moment(current_time).format('YYYY-MM-DD') }}
        <hr>
        发表时间：{{ moment(current_time).fromNow() }}
        <hr>
    </div>

{% endblock %}



{# 导入js #}
{% block scripts %}
    {{ super() }}
{#    改写成中文,默认为英文 #}
    {{ moment.include_moment()}}
    {{ moment.locale('zh-CN') }}
{% endblock %}

flask_app/APP/templates/original_form.html
{% extends 'bace.html' %}

{% block content %}
    <div align="center">
        <h1>hello {{ username | default('god',true) }}</h1>
        <form action="" method="post">
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">username</span>
                <input name='username' type="text" class="form-control" placeholder="Username"
                       aria-describedby="basic-addon1">
            </div>
            <hr>
            <input type="submit" value="log in">
        </form>
    </div>

{% endblock %}